// forms page
import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import Single from "../components/UI/Layout/Single";

const Forms: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Clrty New Forms</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Single title="Forms">table here</Single>
    </>
  );
};

export default Forms;
