// dashboard page
import type { NextPage } from "next";
import Head from "next/head";
import Login from "../components/Auth/LoginForm";
import { trpc } from "../utils/trpc";
import Layout from "../components/UI/Layout/Main";

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout title={"Dashboard"}>content</Layout>
    </>
  );
};

export default Home;
